[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read", path = "zk_proof.json" },
    { access = "read", path = ".env" },
]

[rpc_endpoints]
sepolia = "${RPC_URL}"
